catalogue/urls.py
from django.urls import path
from django.conf.urls import url

from catalogue import views

app_name = 'catalogue'
urlpatterns = [
    path('', views.catalogue, name='index'),
    url(r'(?P<item_slug>[\w\.%+-]+)/$', views.catalogue_item, name='catalogue_item')
]

orders/urls.py
from django.urls import path
from django.conf.urls import url

from orders import views

app_name = 'orders'
urlpatterns = [
    path('', views.order, name='index'),
    path('order_add_item', views.order_add_item, name='order_add_item')]

tombstones18/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include

from tombstones18 import views

from catalogue.urls import urlpatterns as catalogue_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('catalogue/', include('catalogue.urls', namespace='catalogue'), name='catalogue'),
    path('services/', views.services, name='services'),
    path('contact/', views.contact, name='contact'),
    path('orders/', include('orders.urls', namespace='orders'), name='orders')]

if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalogue/models.py
from django.db import models


class Stone(models.Model):
    name = models.CharField(max_length=150)
    image = models.ImageField()
    description = models.TextField()

    def __str__(self):
        return f'{self.name}'


class Category(models.Model):
    name = models.CharField(max_length=150)
    order = models.IntegerField()

    def __str__(self):
        return f'Category {self.name}'

    class Meta:
        ordering = ['order']


class Item(models.Model):
    name = models.CharField(max_length=150)
    slug = models.CharField(max_length=150, unique=True)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True)
    image = models.ImageField()
    gist = models.CharField(max_length=150)
    description = models.TextField()
    customizable_stone = models.BooleanField()
    size = models.CharField(max_length=100)
    available_stone = models.ManyToManyField(Stone)

    def __str__(self):
        return f'{self.name}'

orders/models.py
import uuid
import django.contrib.auth.models
import services.models
import catalogue.models
from django.db import models
from functools import reduce


ORDER_STATUS_NOT_COMMITED  = 0
ORDER_STATUS_COMMITED      = 1
ORDER_STATUS_CONFIRMED     = 2
ORDER_STATUS_DELIVERED     = 3


ORDER_STATUS_CHOICES = (
    (ORDER_STATUS_NOT_COMMITED,    'not commited'),
    (ORDER_STATUS_COMMITED,        'commited'),
    (ORDER_STATUS_CONFIRMED,       'confirmed'),
    (ORDER_STATUS_DELIVERED,       'delivered'))


def order_status_str(order_status):
    for i, s in ORDER_STATUS_CHOICES:
        if i == order_status:
            return s
    raise LookupError(f'undefined status state: {order_status}')


class OrderItem(models.Model):
    order = models.ForeignKey('Order', on_delete=models.CASCADE)
    item = models.ForeignKey(catalogue.models.Item, on_delete=models.SET_NULL, null=True)
    quantity = models.IntegerField()


class OrderManager(models.Manager):
    def create_or_add_item(self, client_uuid, item_id):
        item = catalogue.models.Item.objects.get(id=item_id)
        order = None
        try:
            order = self.get(client_uuid=client_uuid)
        except Order.DoesNotExist:
            order = self.create(client_uuid=client_uuid, state=ORDER_STATUS_NOT_COMMITED)
        
        try:
            order_item = OrderItem.objects.get(order=order, item=item)
        except OrderItem.DoesNotExist:
            order_item = OrderItem.objects.create(order=order, item=item, quantity=0)
        order_item.quantity += 1
        order_item.save()


class Order(models.Model):
    client_uuid = models.UUIDField()
    state = models.IntegerField(choices=ORDER_STATUS_CHOICES, default=0)
    services = models.ManyToManyField(services.models.Service)

    objects = OrderManager()

    @property
    def items(self):
        return OrderItem.objects.filter(order=self)

    @property
    def price(self):
        def add(*args):
            return sum(args)
        return reduce(add, [i.catalogue_item.price for i in OrderItem.objects.get(order=self)])

    def __str__(self):
        return f'Order ({order_status_str(self.state)})'

services/models.py
from django.db import models


class Service(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()
    
    def __str__(self):
        return f'{self.name}'

catalogue/views.py
from django.shortcuts import render
from catalogue import models


def catalogue_item(request, item_slug):
    item = models.Item.objects.get(slug=item_slug)
    return render(request, 'catalogue_item.html', context={'item': item})


def catalogue(request):
    items = models.Item.objects.all()
    return render(request, 'catalogue.html', context={'items': items})

orders/views.py
import uuid
from django.shortcuts import render, redirect
import catalogue.models
from orders.models import Order, ORDER_STATUS_CHOICES


def get_and_map_or(d, k, m, default=None):
    v = d.get('client_uuid')
    if v is None:
        return default
    else:
        return m(v)

def get_and_map_or_lazy(d, k, m, default):
    v = d.get('client_uuid')
    if v is None:
        return default()
    else:
        return m(v)


def order(request):
    client_uuid = get_and_map_or(request.COOKIES, 'client_uuid', uuid.UUID)
    orders = []
    if client_uuid is not None:
        orders = Order.objects.filter(client_uuid=client_uuid).all()
    context={
        'has_orders': len(orders) > 0,
        'orders': orders}
    return render(request, 'orders.html', context=context)


def order_add_item(request):
    response = redirect(request.POST.get('back', '/catalogue'))
    item_id_param = request.POST.get('item_id')
    if item_id_param is None:
        return response
    item_id = int(item_id_param)
    client_uuid = get_and_map_or_lazy(request.COOKIES, 'client_uuid', uuid.UUID, uuid.uuid4)
    response.set_cookie('client_uuid', client_uuid)
    item = catalogue.models.Item.objects.get(id=item_id)
    Order.objects.create_or_add_item(client_uuid, item_id)
    return response

services/views.py
from django.shortcuts import render

# Create your views here.

tombstones18/views.py
from django.shortcuts import render


def home(request):
	return render(request, 'home.html', {})


def services(request):
	return render(request, 'services.html', {})


def contact(request):
	return render(request, 'contact.html', {})


def catalogue(request):
	return render(request, 'catalogue.html', {})

templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <link rel="icon" href="../../favicon.ico">

        <title>Theme Template for Bootstrap</title>

        <!-- Bootstrap core CSS -->
        <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
        <!-- Bootstrap theme -->
        <link href="{% static 'vendor/bootstrap/css/bootstrap-theme.min.css' %}" rel="stylesheet">

        <!-- Custom styles for this template -->
        <link href="{% static 'vendor/bootstrap/css/theme.css' %}" rel="stylesheet">
        <link rel="stylesheet" href="{% static 'css/base.css' %}" />

        <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
        <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
          <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->

        {% block css %}{% endblock %}
    </head>
    <body>

        <!-- Fixed navbar -->
        <nav class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="{% url 'home' %}">Tombstones18</a>
                </div>
                <div id="navbar" class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li><a href="{% url 'catalogue:index' %}">Каталог</a></li>
                        <li><a href="{% url 'services' %}">Услуги</a></li>
                        <li><a href="{% url 'contact' %}">Контакты</a></li>
                        <li><a href="{% url 'orders:index' %}">Заказы</a></li>
                    </ul>
                </div><!--/.nav-collapse -->
            </div>
        </nav>

        <main role="main">
            {% block main %}
            {% endblock %}
        </main>

        <!-- Bootstrap core JavaScript
        ================================================== -->
        <!-- Placed at the end of the document so the pages load faster -->
        <script src="{% static 'vendor/jquery-3.3.1.slim.min.js' %}"></script>
        <script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>
        {% block js %}{% endblock %}
    </body>
</html>

templates/catalogue.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block css %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'css/catalogue.css' %}">
{% endblock %}

{% block main %}
    <div class="container catalogue">
        {% for i in items %}
            <a class="panel panel-default" href="{% url 'catalogue:catalogue_item' i.slug %}">
                <div class="panel-heading">
                    {{ i.name }}
                </div>
                <div class="panel-body">
                    <img src="{{ i.image.url }}">
                </div>
                <div class="panel-footer">
                    {{ i.gist }}
                </div>
            </a>
        {% endfor %}
    </div>
{% endblock %}

templates/catalogue_item.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block css %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'css/catalogue_item.css' %}">
{% endblock %}

{% block main %}
    <div class="container catalogue-item">
        <div class="jumbotron">
            <img src="{{ item.image.url }}" width="500" height="500">
            <h2>{{ item.name }}</h2>
            <h3>{{ item.gist }}</h3>
            <p>{{ item.description }}</p>
            <p>Размер: {{ item.size }}</p>
            <p>Цена: 9999 руб.</p>
        <form action="{% url 'orders:order_add_item' %}" method="POST">
            {% csrf_token %}
            <input type="hidden" name="item_id" value="{{ item.id }}">
            <input type="hidden" name="back" value="{{ request.path }}">
            <input type="submit" class="btn btn-info" role="button" value="Заказать">
        </form>
        </div>
    </div>
{% endblock %}

templates/contact.html
{% extends 'base.html' %}

{% block main %}
	<div class="container theme-showcase" role="main">
		<div class="jumbotron">
			<h1>Контакты</h1>
				<br>
				<h2>Адрес</h2>
					<p>г. Ижевск, ул. ХХХ, д. ХХ, вывеска ХХХХХ</p>
				<br>
				<h2>Телефон</h2>
					<h3>Стационарный</h3>
					<p>8(3412)ХХ-ХХ-ХХ</p>
					<h3>Мобильный</h3>
					<p>8(ХХХ)ХХХ-ХХ-ХХ</p>		   
				<br>  
				<h2>Электронная почта</h2>
					<p>ХХХ@ХХХ.ХХ</p>	  
		</div>
	</div>
{% endblock %}

templates/debug_pre.html
{% extends 'base.html' %}

{% block main %}
    <pre>{{ debug }}</pre>
{% endblock %}

templates/home.html
{% extends 'base.html' %}

{% block main %}
	<div class="container theme-showcase" role="main">
		<div class="jumbotron">
			<h1>Tombstones18.ru</h1>
				<h2>Изготовление памятников и надгробий</h2>
					<p>Изготовление памятников и надгробий под заказ. Доставка, установка, гравировка, заливка и облицовка.</p>
		</div>
	</div>
{% endblock %}

templates/orders.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block css %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'css/order.css' %}">
{% endblock %}

{% block js %}
    {{ block.super }}
    <script src="{% static 'js/orders.js' %}"></script>
{% endblock %}

{% block main %}
    <div class="container order-list">
        {% if has_orders %}
            {% for order in orders %}
                <div class="order-list__order-item panel panel-default">
                    <div class="panel-heading" data-target="#order_{{ order.id }}" data-toggle="collapse">
                        <span class="glyphicon glyphicon-collapse-down"></span>
                        {{ order.gist }}
                    </div>
                    <div id="order_{{ order.id }}" class="panel-collapse collapse">
                        <div class="panel-body">
                                <h2>Ваш заказ ожидает вас по адресу: г. Ижевск, ул. ХХХ, д. ХХ, вывеска ХХХХХ.</h2>
                                <h3>Содержимое заказа:</h3>
                            {% for order_item in order.items.all %}
                                <h3>{{ order_item.item.name }}</h3>
                                <img src="{{ order_item.item.image.url }}" width="300" height="300">
                                <h4>{{ order_item.item.gist }}</h4>
                                <p>{{ order_item.item.description }}</p>
                                <p>Размер: {{ item.size }}</p>
                                <p>Цена: 9999 руб.</p>
                                <p>Количество: {{ order_item.quantity }} шт.</p>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            {% endfor %}
        {% else %}
            no orders
        {% endif %}
    </div>
{% endblock %}

templates/services.html
{% extends 'base.html' %}

{% block main %}
	<div class="container theme-showcase" role="main">
		<div class="jumbotron">
			<h1>Услуги</h1>
				<h2>Доставка</h2>
					<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
				<h2>Установка</h2>
					<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
				<h2>Заливка и облицовка</h2>
					<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
				<h2>Гравировка</h2>
					<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
		</div>
	</div>
{% endblock %}